import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { FiArrowUpRight, FiBox, FiClipboard, FiUsers, FiDollarSign } from "react-icons/fi";
import api from "../lib/api";
import { formatPrice } from "../lib/price-format";
import LoadingAnimation from "../components/loadingAnimation";

export default function AdminPage(){
 const [data,setData]=useState({products:[],orders:[],users:[]}); const [loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{try{const [p,o,u]=await Promise.all([api.get('/products'),api.get('/orders'),api.get('/users')]);setData({products:Array.isArray(p.data)?p.data:p.data?.products||[],orders:Array.isArray(o.data)?o.data:o.data?.orders||[],users:Array.isArray(u.data)?u.data:u.data?.users||[]});}finally{setLoading(false)}})()},[]);
 if(loading)return <LoadingAnimation message="Loading dashboard..."/>;
 const revenue=data.orders.filter(o=>o.status!=='Cancelled').reduce((s,o)=>s+Number(o.totalAmount||0),0); const pending=data.orders.filter(o=>['Pending','Confirmed','Processing'].includes(o.status)).length; const low=data.products.filter(p=>Number(p.quantity)<=5).length;
 const cards=[['Products',data.products.length,FiBox,'/admin/products'],['Orders',data.orders.length,FiClipboard,'/admin/orders'],['Customers',data.users.filter(u=>u.role!=='admin').length,FiUsers,'/admin/users'],['Revenue',formatPrice(revenue),FiDollarSign,'/admin/orders']];
 return <div className="space-y-7"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="section-kicker">Overview</p><h2 className="mt-1 text-3xl font-black text-slate-900">Dashboard</h2><p className="mt-1 text-sm text-slate-500">A quick look at your store.</p></div><Link to="/" className="secondary-btn w-fit">Open storefront <FiArrowUpRight/></Link></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label,value,Icon,to])=><Link key={label} to={to} className="stat-card"><div className="stat-icon"><Icon/></div><div><p className="text-sm font-semibold text-slate-500">{label}</p><p className="mt-1 text-2xl font-black text-slate-900">{value}</p></div><FiArrowUpRight className="ml-auto text-slate-300"/></Link>)}</div><div className="grid gap-6 lg:grid-cols-3"><div className="panel lg:col-span-2"><div className="flex items-center justify-between"><div><h3 className="panel-title">Recent orders</h3><p className="panel-subtitle">Latest customer activity</p></div><Link to="/admin/orders" className="text-sm font-bold text-blue-600">View all</Link></div><div className="mt-5 divide-y">{data.orders.slice(0,6).map(o=><div key={o._id||o.orderId} className="flex items-center gap-3 py-4"><div className="order-avatar"><FiClipboard/></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{o.orderId||'Order'}</p><p className="truncate text-xs text-slate-500">{o.user?.name||o.user?.email||'Customer'}</p></div><div className="text-right"><p className="text-sm font-black">{formatPrice(o.totalAmount)}</p><span className="status-pill">{o.status}</span></div></div>)}{data.orders.length===0&&<p className="py-10 text-center text-sm text-slate-400">No orders yet.</p>}</div></div><div className="panel"><h3 className="panel-title">Store alerts</h3><p className="panel-subtitle">Things that may need attention</p><div className="mt-5 space-y-3"><div className="alert-card"><span>📦</span><div><b>{low}</b><p>products have 5 or fewer items in stock.</p></div></div><div className="alert-card"><span>🧾</span><div><b>{pending}</b><p>orders are still being processed.</p></div></div><div className="alert-card"><span>👥</span><div><b>{data.users.length}</b><p>registered accounts in your store.</p></div></div></div></div></div></div>;
}
