import { useContext, useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { GoogleLogin } from "@react-oauth/google";
import { FiArrowLeft, FiEye, FiEyeOff } from "react-icons/fi";
import UserContext from "../context/userContext";

export default function RegisterPage() {
  const { register, googleLogin, isAuthenticated } = useContext(UserContext);
  const navigate = useNavigate(); const [name,setName]=useState(""); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [confirm,setConfirm]=useState(""); const [show,setShow]=useState(false); const [busy,setBusy]=useState(false); const googleEnabled=Boolean(import.meta.env.VITE_GOOGLE_CLIENT_ID);
  useEffect(()=>{if(isAuthenticated) navigate("/",{replace:true})},[isAuthenticated,navigate]);
  const submit=async(e)=>{e.preventDefault();if(password.length<6)return; if(password!==confirm)return;setBusy(true);const r=await register(name.trim(),email.trim(),password);setBusy(false);if(r.success)navigate("/login",{replace:true});};
  const google=async(r)=>{if(!r?.credential)return;setBusy(true);const result=await googleLogin(r.credential);setBusy(false);if(result.success)navigate("/",{replace:true});};
  return <div className="auth-shell"><div className="auth-showcase"><Link to="/" className="text-white/80 hover:text-white"><FiArrowLeft/> Back to store</Link><div className="mt-auto"><div className="brand-mark mb-6 bg-white text-slate-900">iC</div><h1 className="text-4xl font-black">Join the<br/><span className="text-blue-400">i-Computers family.</span></h1><p className="mt-5 max-w-md text-slate-300">Create an account and keep your shopping, orders and profile in one place.</p></div></div><div className="auth-card-wrap"><div className="w-full max-w-md"><div className="auth-card"><div className="mb-6"><p className="section-kicker">Create account</p><h2 className="mt-2 text-3xl font-black">Get started</h2><p className="mt-2 text-sm text-slate-500">It only takes a minute.</p></div>{googleEnabled&&<><GoogleLogin onSuccess={google} onError={()=>{}} width="100%" text="signup_with" shape="rectangular" theme="outline" size="large"/><div className="my-4 flex items-center gap-3 text-xs text-slate-400"><span className="h-px flex-1 bg-slate-200"/>OR<span className="h-px flex-1 bg-slate-200"/></div></>}<form onSubmit={submit} className="space-y-4"><label className="field-label">Full name<input className="field-input" value={name} onChange={e=>setName(e.target.value)} required minLength={2} placeholder="Your name"/></label><label className="field-label">Email<input className="field-input" type="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="you@example.com"/></label><label className="field-label">Password<div className="relative"><input className="field-input pr-12" type={show?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} required minLength={6} placeholder="At least 6 characters"/><button type="button" className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400" onClick={()=>setShow(v=>!v)}>{show?<FiEyeOff/>:<FiEye/>}</button></div></label><label className="field-label">Confirm password<input className="field-input" type={show?"text":"password"} value={confirm} onChange={e=>setConfirm(e.target.value)} required placeholder="Repeat password"/></label><button disabled={busy} className="primary-btn w-full">{busy?"Creating...":"Create Account"}</button></form><p className="mt-6 text-center text-sm text-slate-500">Already have an account? <Link className="font-bold text-blue-600" to="/login">Sign in</Link></p></div></div></div></div>;
}
