import { useEffect, useMemo, useState } from "react";
import { FiShield, FiUserCheck, FiUserX, FiSearch } from "react-icons/fi";
import toast from "react-hot-toast";
import api from "../../lib/api";
import BlockUserModal from "../../components/blockUserModal";
import ChangeRoleOfUserModal from "../../components/changeRoleOfUserModal";
import LoadingAnimation from "../../components/loadingAnimation";

export default function AdminUsersPage(){
 const [users,setUsers]=useState([]),[search,setSearch]=useState(''),[filter,setFilter]=useState('All'),[selected,setSelected]=useState(null),[modal,setModal]=useState(null),[loading,setLoading]=useState(true);
 const load=async()=>{try{setLoading(true);const {data}=await api.get('/users');setUsers(Array.isArray(data)?data:data.users||[])}catch(e){toast.error(e.response?.data?.message||'Failed to load users.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>users.filter(u=>{const q=search.toLowerCase().trim();return(!q||u.name?.toLowerCase().includes(q)||u.email?.toLowerCase().includes(q))&&(filter==='All'||u.role===filter)}),[users,search,filter]);
 const update=(u)=>{if(!u)return;setUsers(old=>old.map(x=>(x._id||x.id)===(u._id||u.id)?{...x,...u}:x));setSelected(null);setModal(null)};
 if(loading)return <LoadingAnimation message="Loading users..."/>;
 return <div className="space-y-6"><div><p className="section-kicker">People</p><h2 className="mt-1 text-3xl font-black">Users</h2><p className="mt-1 text-sm text-slate-500">Manage customers and administrator access.</p></div><div className="panel"><div className="flex flex-col gap-3 md:flex-row"><div className="relative flex-1"><FiSearch className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by name or email..." className="field-input pl-10"/></div><select value={filter} onChange={e=>setFilter(e.target.value)} className="field-input md:max-w-48"><option>All</option><option value="customer">Customers</option><option value="admin">Admins</option></select></div></div><div className="panel overflow-hidden p-0"><div className="overflow-x-auto"><table className="min-w-[760px] w-full text-left"><thead className="border-b bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-4">User</th><th className="px-5 py-4">Role</th><th className="px-5 py-4">Status</th><th className="px-5 py-4 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map(u=>{const admin=u.role==='admin';return <tr key={u._id||u.id} className="hover:bg-slate-50/70"><td className="px-5 py-4"><div className="flex items-center gap-3"><span className="avatar">{(u.name||'U')[0].toUpperCase()}</span><div><p className="font-bold text-slate-800">{u.name||'Unnamed user'}</p><p className="text-xs text-slate-500">{u.email}</p></div></div></td><td className="px-5 py-4"><span className={`inline-flex items-center gap-1 rounded-full px-3 py-1 text-xs font-bold ${admin?'bg-indigo-50 text-indigo-700':'bg-slate-100 text-slate-600'}`}>{admin?<FiShield/>:<FiUserCheck/>}{admin?'Admin':'Customer'}</span></td><td className="px-5 py-4"><span className={`rounded-full px-3 py-1 text-xs font-bold ${u.isBlocked?'bg-red-50 text-red-600':'bg-emerald-50 text-emerald-600'}`}>{u.isBlocked?'Blocked':'Active'}</span></td><td className="px-5 py-4"><div className="flex justify-end gap-2"><button onClick={()=>{setSelected(u);setModal('role')}} className="rounded-lg border px-3 py-2 text-xs font-bold hover:bg-white">Change Role</button><button onClick={()=>{setSelected(u);setModal('block')}} className={`rounded-lg px-3 py-2 text-xs font-bold ${u.isBlocked?'bg-emerald-50 text-emerald-700':'bg-red-50 text-red-600'}`}>{u.isBlocked?<FiUserCheck/>:<FiUserX/>}{u.isBlocked?'Unblock':'Block'}</button></div></td></tr>})}</tbody></table></div>{filtered.length===0&&<div className="py-16 text-center text-sm text-slate-400">No users found.</div>}</div>{modal==='block'&&<BlockUserModal user={selected} onClose={()=>setModal(null)} onSuccess={update}/>} {modal==='role'&&<ChangeRoleOfUserModal user={selected} onClose={()=>setModal(null)} onSuccess={update}/>}</div>;
}
